/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import modelo.SqlMateriales;

/**
 *
 * @author jabes
 */
public class Consultar extends javax.swing.JFrame {

    private String tipoMaterial;

    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("LISTA DE MATERIALES:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel1)
                .addContainerGap(367, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setTipoMaterial(String tipoMaterial) {
        this.tipoMaterial = tipoMaterial;
        actualizarTabla(tipoMaterial);
    }

    private void actualizarTabla(String tipoMaterial) {
        DefaultTableModel model = new DefaultTableModel();
        SqlMateriales modSql = new SqlMateriales();

        switch (tipoMaterial) {
            case "cds":                
                model.setColumnIdentifiers(new Object[]{"ID", "CodigoIdentificacion", "Titulo", "Artista", "Genero", "Duracion", "NumeroCanciones", "Ubicacion", "Unidades", "UnidadesPrestados", "UnidadesDisponibles"});
                modSql.consultarCds(model);
                break;
            case "libros":
                model.setColumnIdentifiers(new Object[]{"ID", "CodigoIdentificacion", "Titulo", "Autor", "Paginas", "Editorial", "ISBN", "FechaPublicacion", "Ubicacion", "Unidades", "UnidadesPrestados", "UnidadesDisponibles"});
                modSql.consultarLibros(model);
                break;
            case "obras":
                model.setColumnIdentifiers(new Object[]{"ID", "CodigoIdentificacion", "Titulo", "Autor", "Paginas", "Genero", "FechaPublicacion", "Ubicacion", "Unidades", "UnidadesPrestados", "UnidadesDisponibles"});
                modSql.consultarObras(model);
                break;
            case "revistas":
                model.setColumnIdentifiers(new Object[]{"ID", "CodigoIdentificacion", "Titulo", "Editorial", "Periodicidad", "FechaPublicacion", "Ubicacion", "Unidades", "UnidadesPrestados", "UnidadesDisponibles"});
                modSql.consultarRevistas(model);
                break;
            case "tesis":
                model.setColumnIdentifiers(new Object[]{"ID", "CodigoIdentificacion", "Titulo", "Autor", "Facultad", "FechaPublicacion", "Ubicacion", "Unidades", "UnidadesPrestados", "UnidadesDisponibles"});
                modSql.consultarTesis(model);
                break;
            default:
                break;
        }
        jTable1.setModel(model);

    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        home.frmConsulta = null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
